name: Healthy-Plate
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches: [ master ]

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
      - name: Use Node.js 12. x
        uses: actions/setup-node@v1
        with:
          node-version: 12. x
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
    
      - name: Install and Build 
        run: |
         - npm install
         - npm run client: install
         - npm run client: build
         - npm run start
        
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      
        

 
